# Generated by Django 3.1 on 2020-11-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20201102_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(blank=True, to='shop.Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variation',
            field=models.ManyToManyField(blank=True, to='shop.Variation'),
        ),
    ]
