# Generated by Django 3.1 on 2020-11-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20201102_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='other_image',
            field=models.ManyToManyField(blank=True, to='shop.Image'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
