# Generated by Django 3.1 on 2020-11-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20201106_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
