# Generated by Django 3.1 on 2020-11-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20201107_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='second_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='third_image',
        ),
    ]
